### ISSUE TITLE
Push-Button example

### ISSUE THREAD

**Issue by sleepingshorty** [spirilis/msprf24#19]
Hi.

First thank you very much for the library. It looks great but I have an issue when I try to use the pushbutton-example:

![image](https://cloud.githubusercontent.com/assets/7735619/14976754/c52131b8-110e-11e6-9423-f38ea75618f4.png)

I found that it works, when I change:

![image](https://cloud.githubusercontent.com/assets/7735619/14976762/d0cbf264-110e-11e6-9ba0-342f32341d59.png)

to 

![image](https://cloud.githubusercontent.com/assets/7735619/14976769/de20c8b8-110e-11e6-9246-f6b6ed2b1773.png)

in msprf24.c.

Am I doing something wrong?

I am using Code Composer Studio 6.1.2.00015,
my folder looks like this:
![image](https://cloud.githubusercontent.com/assets/7735619/14976749/ac77a584-110e-11e6-8279-c614fcbd9914.png)

Thanks again.
Kind Regards,
Sleepingshorty

**Comment by aimylios** [comment]
Hi Sleepingshorty,

I just encountered the same issue (CCS 6.2.0.00048 with TI compiler v15.12.3.LTS). There is a comment about this on TI E2E, stating that the function body must exist within the same C file it is being called inline:
https://e2e.ti.com/support/development_tools/code_composer_studio/f/81/p/3557/12729#12729

I guess this behaviour is compiler specific, because the error disappears when I use GCC for MSP430 (v5.3.0.219) instead of the TI compiler.

**Comment by spirilis** [comment]
Interesting.  Yeah I only really tested this with GCC.

**Comment by spirilis** [comment]
I removed the inline for now.  Hopefully that doesn't toast anyone's code... I doubt it (if anything it might shorten the compiled result a bit)

**Comment by sleepingshorty** [comment]
Thank you very much.
